name: C/C++ CI

on: [push, pull_request]

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: |
        sudo apt-get update
        sudo apt-get install -qy libgtkmm-3.0-dev libconfig++-dev libcurl4-openssl-dev libxml2-dev  \
        libgstreamer1.0-dev libsecret-1-dev libunrar-dev libzip-dev libpeas-dev
    - uses: BSFishy/meson-build@v1.0.3
      with:
        action: build
